### ISSUE TITLE
Training the Bag-of-Words Model / 训练词袋

### ISSUE THREAD

**Issue by zzzzxxxx111** [yutongwangBIT/SP-Loop#1]
您好，非常感谢您的工作，请问您公开训练词袋的代码了吗？

**Comment by yutongwangBIT** [comment]
Hello, I appreciate your interest and I'm sorry for getting back to you late. The C++ training code was not originally open-sourced, but based on your suggestion, I'm planning to share it with the community shortly.

**Comment by yutongwangBIT** [comment]
> 您好，非常感谢您的工作，请问您公开训练词袋的代码了吗？

Hi, the code is now added at https://github.com/yutongwangBIT/SP-Loop/tree/master/offline_model_training. Please be attention that this directory is separate from the whole project, you need to compile it independently with C++. Hope you fit that well.

**Comment by zzzzxxxx111** [comment]
非常感谢！！
