### ISSUE TITLE
无法加载词袋

### ISSUE THREAD

**Issue by hdrive** [yutongwangBIT/SP-Loop#2]
```
    string vocabulary_file = pkg_path + "/../support_files/voc_binary_tartan_8u_6.yml.gz";
    cout << "vocabulary_file" << vocabulary_file << endl;
    posegraph_sp.loadVocabulary(vocabulary_file);
    ROS_INFO("Vocabulary LOADED!");
```
"voc_binary_tartan_8u_6.yml.gz" 这个文件，这个文件的描述子是二进制的，但是很久都无法加载成功，"Vocabulary LOADED!" 这个消息一直无法打印；
换 “voc_int_large.yml”可以打印信息，但这个描述子是[0-255]的。
请问这里是怎么使用的？谢谢~

**Comment by yutongwangBIT** [comment]
您好，

感谢您的问题。我猜想会不会和opencv的版本有关系。这个工作是两年多前，使用ubuntu18.04，opencv版本3.0或者更低。或许您可以单独测试一下关于词袋模型的部分，在offline model training中，这部分没有使用ros，单独的c++项目就可以测试。

如果有问题，我们可以继续讨论。
祝好运！
