### ISSUE TITLE
代码运行

### ISSUE THREAD

**Issue by jerryjifjsdbf** [yutongwangBIT/SP-Loop#3]
请问代码如何配置GPU环境

**Comment by jerryjifjsdbf** [comment]
具体怎么运行的，没搞懂，是在conda环境下跑，还是cpu环境下跑

**Comment by yutongwangBIT** [comment]
您这个是编译问题，和CPU应该无关。看起来是某个‘python3-empy’没安装

**Comment by jerryjifjsdbf** [comment]
这个代码是要在conda环境下编译吗，python3-empy我装过了，应该是conda环境冲突了，我现在直接在conda环境下catkin_make,出现如下问题，麻烦解答一下：
![图片](https://github.com/yutongwangBIT/SP-Loop/assets/130327433/631ff6e1-9f63-4636-9513-ed875378b2c1)
但是我把所有的cmakelist文件中的torch_library都改名了，还是报同样的错

**Comment by yutongwangBIT** [comment]
libtorch的版本会不会不兼容

**Comment by jerryjifjsdbf** [comment]
就是按照你给的步骤：
![image](https://github.com/yutongwangBIT/SP-Loop/assets/130327433/bbb37c1a-00ac-4f9e-8e71-86612c1fed90)

**Comment by yutongwangBIT** [comment]
libtorch的版本需要和你自己电脑显卡兼容
